# Generated by Django 3.0.3 on 2020-02-12 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_roomtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
