# Generated by Django 3.0.3 on 2020-02-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_delete_roomtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='RoomCategory',
            field=models.CharField(choices=[('PREMIUM_KHODIDHAR', 'Premium @ Khodidhar'), ('ECONOMY_KHODIDHAR', 'Economy @ Khodidhar'), ('DORTOIR_KHODIDHAR', 'Dortoir @ Khodidhar'), ('SPECIAL', 'Special'), ('PREMIUM_NAGAO', 'Premium @ Nagao'), ('ECONOMY_NAGAO', 'Economy @ Nagao')], default='PREMIUM_KHODIDHAR', max_length=64),
        ),
    ]
