# Generated by Django 3.0.3 on 2020-02-13 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guest_roomcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='NumberofRooms',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='TypeofRooms',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default='1', max_length=64),
            preserve_default=False,
        ),
    ]
