# Generated by Django 3.0.3 on 2020-02-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0005_auto_20200213_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='NumberofRooms',
        ),
    ]
