# Generated by Django 3.0.3 on 2020-02-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_remove_guest_numberofrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='TypeofRooms',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=64),
        ),
    ]
