# Generated by Django 3.0.3 on 2020-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoomCategory', models.CharField(choices=[('PREMIUM_KHODIDHAR', 'Premium @ Khodidhar'), ('ECONOMY_KHODIDHAR', 'Economy @ Khodidhar'), ('DORTOIR_KHODIDHAR', 'Dortoir @ Khodidhar'), ('SPECIAL', 'Special'), ('PREMIUM_NAGAO', 'Premium @ Nagao'), ('ECONOMY_NAGAO', 'Economy @ Nagao')], max_length=64)),
            ],
        ),
    ]
