# Generated by Django 3.0.3 on 2020-02-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '__first__'),
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodBills',
            new_name='FoodBill',
        ),
    ]
