# Generated by Django 3.0.3 on 2020-02-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_auto_20200228_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbill',
            name='Order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Food.Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='Item_Details',
            field=models.TextField(default=' '),
        ),
    ]
