# Generated by Django 3.0.3 on 2020-03-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0003_auto_20200228_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbill',
            name='Quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
